### ISSUE TITLE
Compile erro on Rust 1.69.0

### ISSUE THREAD

**Issue by anotatta** [carl-erwin/unlimited#10]
rust version: 1.69.0 
Windows 10

Compile error.
`
  Installing unlimited v0.0.5-dev (E:\Documents\unlimited)
    Updating crates.io index
    Updating git repository `https://github.com/carl-erwin/crossterm`
   Compiling unlimited v0.0.5-dev (E:\Documents\unlimited)
error[E0433]: failed to resolve: could not find `unix` in `os`
    --> src\core\buffer\buffer.rs:1017:22
     |
1017 |         use std::os::unix::fs::PermissionsExt;
     |                      ^^^^ could not find `unix` in `os`

error[E0599]: no function or associated item named `from_mode` found for struct `Permissions` in the current scope
    --> src\core\buffer\buffer.rs:1024:45
     |
1024 |             Err(_) => std::fs::Permissions::from_mode(0o600),
     |                                             ^^^^^^^^^ function or associated item not found in `Permissions`

Some errors have detailed explanations: E0433, E0599.
For more information about an error, try `rustc --explain E0433`.
error: could not compile `unlimited` due to 2 previous errors
error: failed to compile `unlimited v0.0.5-dev (E:\Documents\unlimited)`, intermediate artifacts can be found at `E:\Documents\unlimited\target`

`

**Comment by carl-erwin** [comment]
Hi, thank you for your report. It's been a long time since I built for windows :-)

It is fixed on master in 616d269af19790122c21b5226531081cad4c78df

**Comment by anotatta** [comment]
Super. Thanks.
